apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancing-service
  labels:
    app: nginx-service-app
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
    - nodePort: 31000
      port: 80
      targetPort: 80
