apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-disk-claim
spec:
  resources:
    requests:
      storage: 15Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: fast # coming from metadata.name in storage-class.yaml
