apiVersion: v1
kind: Pod
metadata:
  name: redis-pod2
spec:
  containers:
    - name: redis-container2
      image: redis
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
  restartPolicy: Never
