apiVersion: v1
kind: Service
metadata:
  name: frontend-load-balancer-service
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: guestbook
    tier: frontend
  ports:
    - port: 80
