apiVersion: v1
kind: Service
metadata:
  name: redis-slave-cluster-ip-service
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: redis
    role: slave
    tier: backend
  ports:
    - port: 6379
      targetPort: 6379
