apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: {{.Values.scale}}
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:{{.Values.tag}}
          ports:
            - containerPort: 80
