apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  containers:
    - name: pv-container
      image: nginx
      volumeMounts:
        - mountPath: /test-pv
          name: test-volume
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: my-disk-claim # coming from metadata.name in gce-persisten-volume-claim.yaml
